### ISSUE TITLE
Coding Error - Main Screen

### ISSUE THREAD

**Issue by Ant5246** [MacNaab/ProjectHospital_Gynecology#1]
upon installing this MOD I get several errors on the main screen, possibly since the latest update install. It is only when I install this MOD and not any other. 

Also several other script errors show when pressing the 'options' page on the main screen.

Screenshot - https://ibb.co/mDt3wZC & https://ibb.co/68mY3vB

Note I have downloaded this as I have the GOG version , none steam , all other mods work fine however it seems to be 'looking' for the steam directory?

**Comment by MacNaab** [comment]
Hi, could you replace CRP and OBGYN with these two files and see if the errors persist ?
[CRP.zip](https://github.com/MacNaab/ProjectHospital_Gynecology/files/5444522/CRP.zip)
[OBGYN.zip](https://github.com/MacNaab/ProjectHospital_Gynecology/files/5444521/OBGYN.zip)

**Comment by DazPheonix** [comment]
Hi MacNabb Just wanted to state that i also had this issue, the fix you provided solved the issue for me.
Hope this helps

**Comment by MacNaab** [comment]
Thanks for your feedback. I’ll add these version to OBGYN’s Github  then
